# Generated by Django 3.2.5 on 2021-07-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receitas',
            new_name='Receita',
        ),
    ]
