# Generated by Django 3.2.5 on 2021-07-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_rename_receitas_receita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='passos',
            new_name='ingredientes',
        ),
    ]
