# Generated by Django 3.2.5 on 2021-07-17 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receitas', '0004_receita_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='autor',
        ),
        migrations.AddField(
            model_name='receita',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receitas', to=settings.AUTH_USER_MODEL),
        ),
    ]
