# Generated by Django 3.2.5 on 2021-07-17 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_auto_20210717_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='owner',
            new_name='autor',
        ),
    ]
